CREATE TABLE notificacao (
    id VARCHAR(36) PRIMARY KEY,
    usuario_id VARCHAR(36) NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    autor_id VARCHAR(36) NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    tipo VARCHAR(20) NOT NULL,
    post_id VARCHAR(36) REFERENCES post(id) ON DELETE CASCADE,
    conteudo VARCHAR(200) NOT NULL,
    lida BOOLEAN DEFAULT FALSE NOT NULL,
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
